### PR TITLE
Upgrade to Python3

### PR DESCRIPTION
**Pull request by frankcrawford**
Here is an update to Python3, passed through 2to3 and then fixing up obvious issues.

I've tested sshfp well, tlsa and openpgpkey a bit, and haven't really done any testing with ipseckey, although it appears to be fine.

I've also done a minor fixup for the tlsa documentation.

### CODE REVIEW

**Comment by stoecker** [comment]
I found two points:
1) You disabled the Punnycode conversion in tlsa. That's not good. When you enter a domain like dstöcker.de it should work with xn--dstcker-c1a.de instead.
2) There are some cases of duplicate brackets for print(()). Are they really necessary?

**Comment by frankcrawford** [comment]
I thing the print(()) are errors, and I'll fix them up.

The disable Punnycode conversion is an issue that all strings are now Unicode and needs a different conversion to the one you currently have.  I'll investigate how to handle it.

I'll also probably push an update to the fedora and maybe debian build scripts.

**Comment by frankcrawford** [comment]
@stoecker Okay, fixed up both those issues with tlsa, although I don't know the correct arguments to test out the punnycode conversion.
Please check it and let me know if there are any further issues.
I'll then fix up the build scripts.

**Comment by stoecker** [comment]
Very easy test :-)

> # tlsa dstöcker.de
> Got a certificate with Subject: /C=DE/ST=Germany/L=Bischofswerda/O=Stoecker.eu/CN=dstoecker.eu/emailAddress=cert@dstoecker.de
> _443._tcp.xn--dstcker-c1a.de. IN TLSA 3 0 1 b96703d2d8c5ae0bbe0371b58b597b62e59fde04a1b46d444d3d9f9addf4e344
> Got a certificate with Subject: /C=DE/ST=Germany/L=Bischofswerda/O=Stoecker.eu/CN=dstoecker.eu/emailAddress=cert@dstoecker.de
> _443._tcp.xn--dstcker-c1a.de. IN TLSA 3 0 1 b96703d2d8c5ae0bbe0371b58b597b62e59fde04a1b46d444d3d9f9addf4e344

**Comment by stoecker** [comment]
P.S. Don't forget to add your credits to the README :-)

**Comment by frankcrawford** [comment]
Thanks.

I'll push the updates to the build files tomorrow and that should be all you need.

**Comment by letoams** [comment]
On Wed, 30 Oct 2019, Frank Crawford wrote:

> I'll push the updates to the build files tomorrow and that should be all you need.

Once that's done, we will do a new version release.

Paul

**Comment by frankcrawford** [comment]
Okay, now update the build files.  Unfortunately I haven't tested the debian build files, but they look correct.

**Pull request merged**
