### PR TITLE
add SNI to TLSA tool and don't prevent generating port 25 data for lo…

### PR DESCRIPTION
**Pull request by stoecker**
Fixes issue #2 and also allows usage of SNI which is supported by recent M2Crypto versions.

### CODE REVIEW

**Comment by letoams** [comment]
merged

**Comment by stoecker** [comment]
You're sure this is merged? Not here: https://github.com/letoams/hash-slinger/commits/master

**Comment by letoams** [comment]
Sorry, need to push out to github still

**Comment by stoecker** [comment]
P.S. I have a fix for STARTTLS issue ready as well, but first need to get my changes into M2Crypto.

**Comment by stoecker** [comment]
> Sorry, need to push out to github still

And?

**Comment by letoams** [comment]
On Wed, 9 Dec 2015, stoecker wrote:

> ```
>   Sorry, need to push out to github still
> ```
> 
> And?

Sorry, just did it.

**Pull request closed without merging**
